import * as fs from "fs";
import * as path from "path";

import { ethers, network } from "hardhat";

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`Missing required environment variable: ${name}`);
  return value;
}

async function main() {
  const usdcAddress = requireEnv("ARC_USDC_ADDRESS");
  if (!ethers.isAddress(usdcAddress)) {
    throw new Error("ARC_USDC_ADDRESS must be a valid address");
  }

  const expectedChainId = Number(requireEnv("ARC_CHAIN_ID"));
  const actualNetwork = await ethers.provider.getNetwork();
  const actualChainId = Number(actualNetwork.chainId);
  if (actualChainId !== expectedChainId) {
    throw new Error(
      `Chain ID mismatch: expected ${expectedChainId}, got ${actualChainId}`,
    );
  }

  const [deployer] = await ethers.getSigners();
  if (!deployer) throw new Error("No deployer signer available");

  console.log(`Network: ${network.name}`);
  console.log(`Chain ID: ${actualChainId}`);
  console.log(`Deployer: ${deployer.address}`);
  console.log(`USDC token: ${usdcAddress}`);

  const hub = await ethers.deployContract("ArcOpenRailsHubV1", [usdcAddress]);
  await hub.waitForDeployment();
  const hubAddress = await hub.getAddress();
  const registry = {
    network: network.name,
    chainId: actualChainId,
    arcUsdcAddress: usdcAddress,
    arcOpenRailsHubV1: hubAddress,
    deployer: deployer.address,
    deployedAt: new Date().toISOString(),
    explorerBaseUrl: process.env.ARC_EXPLORER_BASE_URL || "",
    notes: "Generated by scripts/deploy-openrails.ts. Secrets and private RPC URLs are intentionally excluded.",
  };

  console.log(`ArcOpenRailsHubV1 deployed: ${hubAddress}`);
  console.log(JSON.stringify(registry, null, 2));

  const registryPath = process.env.OPENRAILS_DEPLOYMENT_REGISTRY_PATH;
  if (registryPath) {
    const resolvedPath = path.resolve(registryPath);
    fs.mkdirSync(path.dirname(resolvedPath), { recursive: true });
    fs.writeFileSync(resolvedPath, `${JSON.stringify(registry, null, 2)}\n`);
    console.log(`Deployment registry written: ${resolvedPath}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
