export const HUB_ABI = [
  {
    type: "event",
    name: "PaycardProvisioned",
    inputs: [
      { name: "paycardId", type: "bytes32", indexed: true },
      { name: "payer", type: "address", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "metadataHash", type: "bytes32" },
      { name: "poolAllocation", type: "uint256" },
      { name: "flowVelocityPerSecond", type: "uint256" },
      { name: "genesisTimestamp", type: "uint256" },
      { name: "lifespanSeconds", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "SettlementFlushed",
    inputs: [
      { name: "paycardId", type: "bytes32", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "amountWithdrawn", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "ResidualDeltaReclaimed",
    inputs: [
      { name: "paycardId", type: "bytes32", indexed: true },
      { name: "recoveryVault", type: "address", indexed: true },
      { name: "varianceSwept", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "registry",
    stateMutability: "view",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [
      { name: "payer", type: "address" },
      { name: "recipient", type: "address" },
      { name: "metadataHash", type: "bytes32" },
      { name: "totalAllocationPool", type: "uint256" },
      { name: "availableBalance", type: "uint256" },
      { name: "flowVelocityPerSecond", type: "uint256" },
      { name: "genesisTimestamp", type: "uint256" },
      { name: "lifespanSeconds", type: "uint256" },
      { name: "lastCheckpointEpoch", type: "uint256" },
      { name: "residualDeltaRecipient", type: "address" },
      { name: "operationalStatus", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "accountNonceTracks",
    stateMutability: "view",
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "openPaycardChannel",
    stateMutability: "nonpayable",
    inputs: [
      { name: "paycardId", type: "bytes32" },
      { name: "metadataHash", type: "bytes32" },
      { name: "recipient", type: "address" },
      { name: "totalAllocationPool", type: "uint256" },
      { name: "flowVelocityPerSecond", type: "uint256" },
      { name: "genesisTimestamp", type: "uint256" },
      { name: "lifespanSeconds", type: "uint256" },
      { name: "residualDeltaRecipient", type: "address" },
      { name: "envelopeSignature", type: "bytes" },
      { name: "nonceChannel", type: "uint256" },
      { name: "nonceValue", type: "uint256" },
      { name: "payer", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "claimWildcardPaycardChannel",
    stateMutability: "nonpayable",
    inputs: [
      { name: "paycardId", type: "bytes32" },
      { name: "metadataHash", type: "bytes32" },
      { name: "claimRecipient", type: "address" },
      { name: "totalAllocationPool", type: "uint256" },
      { name: "flowVelocityPerSecond", type: "uint256" },
      { name: "genesisTimestamp", type: "uint256" },
      { name: "lifespanSeconds", type: "uint256" },
      { name: "residualDeltaRecipient", type: "address" },
      { name: "envelopeSignature", type: "bytes" },
      { name: "nonceChannel", type: "uint256" },
      { name: "nonceValue", type: "uint256" },
      { name: "payer", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "processDripSettle",
    stateMutability: "nonpayable",
    inputs: [{ name: "paycardId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "flushResidualDelta",
    stateMutability: "nonpayable",
    inputs: [{ name: "paycardId", type: "bytes32" }],
    outputs: [],
  },
] as const;

export const USDC_ABI = [
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  // EIP-2612 permit reads (Arc USDC supports permit) — used for gasless approvals.
  {
    type: "function",
    name: "nonces",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "name",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "version",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
] as const;
